markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygment

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

excerpt_separator: <!--more-->

url: https://garoevans.com

paginate: 5
paginate_path: "/blog/page/:num/"

gems:
  - jekyll-redirect-from
  - jekyll-paginate
