# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            GAROEVANS
tagline:          'Developer, Apprentice, Father & Husband'
description:      'A dumping ground for Gareth Evans: Developer, Apprentice, Father & Husband'
url:              http://garoevans.com

author:
  name:           'Gareth Evans'
  url:            https://twitter.com/garoevans

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/garoevans/garoevans.github.io

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
