# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gareth Evans
tagline:          'Principal Developer at Switch Concepts'
description:      'Gareth Evans: Principal Developer at Switch Concepts'
url:              http://garoevans.com

author:
  name:           'Gareth Evans'
  url:            https://twitter.com/garoevans

paginate:         5
paginate_path:   '/page/:num/'

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/garoevans/garoevans.github.io

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

gems:
  - jekyll-redirect-from
